namespace: spring-microservices

resources:
  - k8s/00-namespace.yaml
  - k8s/01-configmap.yaml
  - k8s/02-postgres-deployment.yaml
  - k8s/03-auth-deployment.yaml
  - k8s/04-user-deployment.yaml
  - k8s/05-gateway-deployment.yaml
  - k8s/06-networkpolicy.yaml

secretGenerator:
  - name: app-secrets
    envs:
      - .env
  - name: user-service-env
    envs:
      - user-service/.env