server:
  port: 5000

spring:
  application:
    name: GATEWAY_SERVICE
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: ${AUTH_MICROSERVICE}
              predicates:
                - Path=/api/auth/**

            - id: user-service-route
              uri: ${USER_MICROSERVICE}
              predicates:
                - Path=/api/users/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway