apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: spring-microservices
data:
  AUTH_MICROSERVICE: "http://auth-service:5001"
  USER_MICROSERVICE: "http://user-service:5002"
  JWT_ISSUER: "auth-token-microservice-issue"
