apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: spring-microservices
type: Opaque
stringData:
  DB_USERNAME: "CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME"
  INTERNAL_API_KEY: "CHANGE_ME"
  SUPER_ADMIN_EMAIL: "CHANGE_ME"
  SUPER_ADMIN_USERNAME: "CHANGE_ME"
  SUPER_ADMIN_PASSWORD: "CHANGE_ME"
