apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: spring-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: loza64/gateway-service:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: SERVER_PORT
              value: "5000"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 5000
            initialDelaySeconds: 15   # <-- Da un respiro de 15s para que Spring Cloud Gateway levante
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 5000
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 5000
            periodSeconds: 15
          resources:
            requests:
              cpu: "150m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: spring-microservices
spec:
  type: LoadBalancer # Único punto expuesto hacia afuera
  selector:
    app: gateway-service
  ports:
    - port: 80
      targetPort: 5000